### ISSUE TITLE
remove the "Blockchain-Security-Framework" on github Deepak lier. 

### ISSUE THREAD

**Issue by EvertonMelo** [OWASP/Blockchain-Security-Framework#3]
Appreciate the time you have taken to write this. 
**stop the lier, you closed the issue and not use my response**

This would have been very helpful if you could provide ways to fix this project. 
**Okay, let'ts go for your wikipedia. **
**very busy: https://www.owasp.org/index.php?title=Blockchain_Security_Framework&action=history  don't make me cry**

The ways to get involved in the project are already detailed at the project page link on the OWASP website - https://www.owasp.org/index.php/Blockchain_Security_Framework
**and you Github? for what?**
**Do not you like reviews?** 

While most actions seem generic and useless to you,
**for me? show me the one example? in the real world please. not those in your head.**
**Tell a github who has something you've reported.**
**you impose rules on others you do not even test. they are useless even to you. can not be reviewed.**

please understand that these details were reviewed by OWASP before finalizing that the project can be created.
**details were reviewed by OWASP, okay 11https://github.com/OWASP/Blockchain-Security-Framework/commit/808233457bba44f23318bf728406b255e153a546
 and 12/January until now, nothing?**
** https://www.owasp.org/index.php?title=Blockchain_Security_Framework&action=history** 

stop lying, no one can review something that has not yet been done.
it is sad that political people who barely conceal facts use OWASP as a shield for their unethical ends.

**Comment by deepakrpandey** [comment]
I could not find anything worth using from your previous response or this one. I will appreciate if you can be polite and communicate what is actually needed to fix the project rather than engage in name calling and shaming. 

Unless you clearly communicate, the issues will be closed. 

Also, please understand that the project page and git repo will be updated as and when necessary. The people working on this project will decide what goes out and when.
